language: rust

rust:
  - nightly

cache: cargo

before_script:
  - rustup component add rustfmt-preview --toolchain nightly

script:
  - cargo +nightly fmt -- --check
  - cargo build -v
  - cargo test -v