language: rust

rust:
  - nightly

cache: cargo

before_script:
  - rustup component add rustfmt-preview --toolchain nightly

script:
  - cargo build -v
  - cargo fmt --all -- --check -v
  - cargo test -v