language: rust

rust: nightly

allow_failures:
  - rust: nightly

cache: cargo

before_script:
  - rustup component add rustfmt-preview --toolchain nightly

script:
  - cargo fmt --all -- --check -v
  - cargo build -v
  - cargo test -v

