[package]

name = "llamadb"
version = "0.1.0"
authors = ["Dan Spencer <dan@atomicpotato.net>", "Constantine Solovev <constantine@fluence.one>"]

description = ""

[dependencies]
log = "0.3"

[dev-dependencies]
env_logger = "0.3"
